apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Mu9vTJykU5TagZbPcyXDr6KR0MX2hNHvtA7q8TwdSoBsVp3pHPwvCkodsUQLZ4suEP+uQDbyuU2ZjqzKb8El5Vb17f+XUdnIPQjw13SS9E4z,iv:wr9KFVCFDqYeSrEjepg0auIC/MMuh8Ssp9JblhM2cvc=,tag:GDfVKY11CsaoR4AbRL5bGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zjr5rpsktv5l8l8ums23ghkffvckmlpyk46k226yphqlavfskuhs9as37k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR3JqMjNtdnQ1SGQ2UW5w
            M21PdEx5Q0lOZjVKNEQvM3JjVy8rQ0pXcVJvCldHd0g1N0tVL0I2QXAwK1hDbG1F
            VHk2YWUxM0w2dVNZZm1VR1VKK1J0aVEKLS0tIHhQOFUycDVlZWZlWlFlYldZamgw
            YWhnaEx1N1FYUDFGNU4yM3JocnN2L2sK4IB/xOBmW2TmjAI7sqz0pmkYdYZvnyEp
            WffBusWlylQNH29vt4dww3se65TKcNDqtY3R08J6ln4WWTUSJnScZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T03:57:38Z"
    mac: ENC[AES256_GCM,data:XaJx/7KaR8nne8sxOYdMG9f2sSPo42SrZ6aLDVr/ROqqhy2re6FHWTo2CW+sJ9uh+YghTcbx2uNNAkcKoPS0VBrO8aFnfpJVr4oR0a3BzDqKTu7p5O+iZKxHI3OYd4o6Uq5zDAih6OX25sKt1h1fiWAY4Jd53+4BHYG4hEP7zgI=,iv:PsS3m3e+KvYVcUgdGUuuLYoSCPjhZr7hzypwsPxBUe8=,tag:wIaIDpT2+s39gnH/NEsK9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
