apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5sA0FK8JhbZhEJW3EeaGLNOsixFhv48Z0qgLiyakNWg=,iv:aWotSjV2fVeLdrzR3o1I7kmbRuHjjUp6NF2hr2HlOxg=,tag:VH4sZVhXjIZD3hMPvNvzvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zjr5rpsktv5l8l8ums23ghkffvckmlpyk46k226yphqlavfskuhs9as37k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcGVDN3RYcDNISGxjVmh5
            cTlsSHU2RHcyelJ2eEJ1Z3l6MExsYUQ4blVNCkU4ODI3VEVWbkliajFYRUMwWWZo
            emZZTVEvNG1TNFErRERvc0c5QzV4YlkKLS0tIEIxaUFPSjVleEtnbGVFcmRpc2Nk
            clNweld3QkRHOWg0TlBOSWZKdE16b1UKSeU6FAnTSYt+lZuMFNj23RedTDjvr7xi
            dilBcAgs6apAjOwdTPOT1KsQwc/NqghQ+WKQOGeNNLb/BtfYOyKi1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T04:45:52Z"
    mac: ENC[AES256_GCM,data:+qDGTzt+ucLcfgpHE0mbefr8S+pAaYDxY8NSVKa6s4XLHCzh8ucc5H9c05p31putPOF52mUHwcvTMTrOrCWe4uek89TH77vjBhkSbVXeg9Q1FD9HfVl5tzlpea4+oztNHlyPgSC2nmhCS/denyXQEpBFNiCLha6R9AL+76dEfY4=,iv:Gy4HxAcY2BhlqKKmbX48ECuVmAwB4V1cppsOxsC22/0=,tag:o2stnvMhK13nlEcZol1NzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
