apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:v2xmlF2XYgE9htnH6yIv8RpYhKeFRuSFvS79kmk6dxA=,iv:yn7JQPo8HwYqhEl/b+qkCUjZdOIfqNl4LqHyeW/jgN0=,tag:TXlcqiRi7Aa2L/SN8j3Uiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zjr5rpsktv5l8l8ums23ghkffvckmlpyk46k226yphqlavfskuhs9as37k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cEdxcmI0dnJaQlQyT2FF
            T081VnVwb09lK1dvbFEvamxqOEpUTjlOUGo4ClNwc1g5dm5KZzliK0ZwRkU0RjZw
            ZkVoRlRqaE8xUFk5ZE1PeE1uT1Ryb3cKLS0tIEs1YjU3RmxvMCtuSEZsdTZSajZE
            ZWZ3dHBiN1ZpcXpmQUF0c2pPemtTK28KSzY0DHSkpmaJMqQMPBT/eaHxjyJGlUEX
            wCKJIClBrUpSRhOD63wp3XEbE8MICl9RRaSLbT3sqTVQUZR71nbeqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T03:57:38Z"
    mac: ENC[AES256_GCM,data:DlERTLt9jU4ioOkISkB1QrPknFT9iud2q4kJLSRA8T35poMUt3hbL+Dr9v6+jk2RGU7GiwzyKMhqcvbyTh52quxRyU1KWt364Pax4RGZWzOhhJ+xAK01NbxF1GeOluKE2l7yGO2rMmrn6BoeHPMR6SvehMB1X138K05H20R1zpM=,iv:qHV2hGAT7hiu83FIRpdKg20N9iey1RaCScOwDUCUy9g=,tag:gvwKnDeLMKWI0PvceePbqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
